# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part digilentinc.com:genesys2:part0:1.1 available at C:/Xilinx/Vivado/2016.1/data/boards/board_files/genesys2/H/board.xml as part xc7k325tffg900-2 specified in board_part file is either invalid or not available}}  -suppress 
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/curso_dda/0_leds/0_leds.cache/wt [current_project]
set_property parent.project_path D:/curso_dda/0_leds/0_leds.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  D:/curso_dda/0_leds/0_leds.srcs/sources_1/new/shift_reg.v
  D:/curso_dda/0_leds/0_leds.srcs/sources_1/new/counter.v
  D:/curso_dda/0_leds/0_leds.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/curso_dda/0_leds/0_leds.srcs/constrs_1/imports/digilent-xdc-master/Arty-Master.xdc
set_property used_in_implementation false [get_files D:/curso_dda/0_leds/0_leds.srcs/constrs_1/imports/digilent-xdc-master/Arty-Master.xdc]


synth_design -top top -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
